name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
    
jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      
      - name: Check Generated Files
        run: ls -l dist/

      - name: Push Snake Game to output Branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b output
          mv dist/* .
          git add github-snake.svg github-snake-dark.svg ocean.gif
          git commit -m "Generated snake game"
          git push origin output --force
